version: "3"
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - .env.model
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.model
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $PORT
      DATABASE_URL: ${DATABASE_URL}
