name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.test.yml --env-file .env.model up -d
      - run: docker ps
      - run: docker run app npm run test
